### ISSUE TITLE
Editing text fields

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#11]
When you need to edit an existing text, like a name, description or a note, it would be much easier to have the previous text written so you just have to make the corrections and not re-write the whole thing.
Usually users just need to make spelling corrections on these.

A feature related to this that I think could advance the overall usability would be the possibility to edit text fields just by clicking on these, instead by selecting that action from the menu(s).

**Comment by ivanminutillo** [comment]
This issue affects:
- [x] Edit plan title
- [x] Edit plan note
- [x] Edit process title
- [x] Edit process note
- [x] Edit process date
- [x] Edit commitment note
- [x] Edit commitment date
- [x] Edit event sentence
- [x] Edit event note
- [x] Edit event date

**Comment by ivanminutillo** [comment]
> When you need to edit an existing text, like a name, description or a note, it would be much easier to have the previous text written so you just have to make the corrections and not re-write the whole thing.
Usually users just need to make spelling corrections on these.

Done...

> A feature related to this that I think could advance the overall usability would be the possibility to edit text fields just by clicking on these, instead by selecting that action from the menu(s).

I agree with it, although I would not include this improvement in the summercamp milestone, and leave it for the next iteration, does it make sense for you?
