### ISSUE TITLE
Due date of processes

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#12]
**Describe the bug**
When editing the due date of a process the pop-up window is false as it refers to start dates.

**To Reproduce**
1. Go to any process
2. Click on the menu (3 dots on the top-left corner)
3. Select "Edit due date"

**Expected behavior**
Change the text so it refers to end date.
Date appearing as default should be the previous selected one, not the current one.

![due date bug](https://user-images.githubusercontent.com/20679274/42229397-13ef6bfc-7eef-11e8-9a17-60ea64ad6a64.png)

**Comment by ivanminutillo** [comment]
Solved on the new release :) Thanks!
