### ISSUE TITLE
Change the order of the Dashboard columns

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#13]
Below are some suggestions that refer to the view (order of the columns) on the Agent's (1) and on a Network's (2) Dashboard.

1. Personal (Agent's) Dashboard (put Networks column before Plans)
    a) Diary
    b) Networks
    c) Plans 
    d) Inventory

2. Networks Dashboard
    a) Diary
    b) Agents (not Networks as it is mentioned now, as these are mainly participants)
    c) Plans 
    d) Inventory

**Comment by ivanminutillo** [comment]
tried, and you're right...it is much clearer now the dashboard :)
