### ISSUE TITLE
prc ???

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#14]
I see a "prc" clickable link beside my agent's name, on the left main menu.

**Screenshots**
![screenshot-2018-7-3 economic dashboard](https://user-images.githubusercontent.com/20679274/42230278-44b588dc-7ef1-11e8-8fa3-2dc38c3cfb43.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version: 60.0.2 (64-bit)

**Comment by ivanminutillo** [comment]
Solved on the new release, thanks :)
