### ISSUE TITLE
Date's format

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#15]
**Describe the bug**
All date's format should be D/M/Y (image 1) in order to follow the common view of processes (image 2)

**Screenshots**
Image 1
![screenshot-2018-7-3 economic dashboard 1](https://user-images.githubusercontent.com/20679274/42230805-94fb77c4-7ef2-11e8-8774-55ccaa57d356.png)

Image 2
![screenshot-2018-7-3 economic dashboard 3](https://user-images.githubusercontent.com/20679274/42230810-9936b2fe-7ef2-11e8-8677-e274a65fb5d4.png)

**Comment by ivanminutillo** [comment]
Solved on the new release :) thanks!
