### ISSUE TITLE
Multiple processes view

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#16]
**Describe the bug**
I created multiple processes in a row and at some point I couldn't view the last tab.
Even the horizontal scroll bar couldn't reach that far view.

**To Reproduce**
1. Go to 'Create new plan'
2. Then add processes at once, one after another.

**Screenshots**
![screenshot-2018-7-3 economic dashboard](https://user-images.githubusercontent.com/20679274/42231454-3ff73fcc-7ef4-11e8-97d3-b37e3d8e1285.png)

** Additional bug
Immediately after that screen, I clicked on the back arrow and got the following screen which is wrong (it involves a process for a different network... unsaved?)
![screenshot-2018-7-3 economic dashboard 1](https://user-images.githubusercontent.com/20679274/42231896-8091d564-7ef5-11e8-97e2-c46a6c659e14.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version: 60.0.2 (64-bit)

**Comment by ivanminutillo** [comment]
fixed both and improved overall css
