### ISSUE TITLE
Edit dates of plans

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#18]
**Describe the bug**
Possibility to edit the Start and Due dates of the plans should be added too, as you need to edit all information related to a plan.

**Screenshots**
![screenshot-2018-7-3 economic dashboard](https://user-images.githubusercontent.com/20679274/42232056-f6ea82a6-7ef5-11e8-96ff-0314ea97e116.png)

**Comment by ivanminutillo** [comment]
Done, btw plan start date does not exist, it is possible to change only the plan due date.
The other info available is "plannedOn" that is simply the date when the plan is created (and it is immutable)
