### ISSUE TITLE
General Settings edit

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#29]
**Is your feature request related to a problem? Please describe.**
Right now the existing info on General Settings tab is appearing in grey and cannot edit, just write another.

**Describe the solution you'd like**
Provide the capability of editing existing text in General Settings column e.g. Name, e-mail etc

**Describe alternatives you've considered**
Also, another feature would be the capability to upload photo.
Otherwise it should be mentioned, probably on the text box, that a URL is required.

**Comment by ivanminutillo** [comment]
Fixed, and improved the overall Settings UI :)
