### ISSUE TITLE
Cite, Use, Consume actions should not be like Work

### ISSUE THREAD

**Issue by fosterlynn** [opencooperativeecosystem/fc-dashboard#3]
On the citation commitment modal in the kanban view, it should not look like work logging, rather the existing resources matching the requirement should be listed with the ability to cite one (or more).  This also applies to "use" and "consume" commitments. 

This is what it looks like now:
![cite-new](https://user-images.githubusercontent.com/3776081/41486735-51933382-70ab-11e8-8a5e-efb6ecf3c63b.png)

This is an example from Sensorica (use and consume, but cite should work the same way):
![cite-old](https://user-images.githubusercontent.com/3776081/41486753-60d85afc-70ab-11e8-8c11-6c29db807762.png)

**Comment by ivanminutillo** [comment]
I just updated the **EconomicEvent** logging logic.
Right now you can log only events related to the commitment action.
But, currently we have the possibility to freely edit a commitment, changing the action type, due date, unit type, value and note.
Should be possible to edit a commitment after someone else logged some events on it?
Which kind of edit we can allow?
imho it does not make sense to edit the commitment action, nor the commitment resource or the unit type, if events are already logged.
"Edit" should be available to edit complementary information, like the note or due date.

**Comment by fosterlynn** [comment]
Some input:  
First, this is what OCP currently does.  At the end some more thoughts.

This is what you can do when logging work against a commitment.  Some things can't be entered because they should match the commitment.
![log-work](https://user-images.githubusercontent.com/3776081/42630013-fe863cd4-859a-11e8-9764-2a0d903412e6.png)

This is what you can do to log work with no commitment.
![log-unpl-work](https://user-images.githubusercontent.com/3776081/42630044-156871ec-859b-11e8-8c9d-ebcc7fb28ec3.png)

This is what you can currently edit on a commitment.  See below for comment.
![edit-com](https://user-images.githubusercontent.com/3776081/42630068-20e34178-859b-11e8-92d7-65f07dc50a6c.png)

>imho it does not make sense to edit the commitment action, nor the commitment resource or the unit type, if events are already logged.

I agree with this. :+1:  We should tighten it up more than currently in OCP.
