### ISSUE TITLE
Due date of Commitments is set wrong

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#30]
**Describe the bug**
Due date of a new commitment is set on the current date, even if selecting another one when creating it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any Process
2. Click on 'Create a new commitment'
3. Fill in all required fields
4. Set the Due date on any future one
5. Publish the Commitment and see that the Due date set to current one (today's)

**Expected behaviour**
Due date should appear as set by user.

**Screenshots**
That is just an example of a commitment logged today, but set for a future due date.
![screenshot_2018-07-14 economic dashboard](https://user-images.githubusercontent.com/20679274/42725154-b4df70e8-8787-11e8-891f-7886ef6f6024.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Firefox
 - Version 61.0.1 (64-bit)

**Comment by ivanminutillo** [comment]
fixed, thanks :)
