### ISSUE TITLE
Line breaks on Commitment's description

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#31]
**Is your feature request related to a problem? Please describe.**
Description of a Commitment appears with no line breaks and may be confusing if lot of details are entered.

**Describe the solution you'd like**
Description of Commitments should use line breaks.

**Additional context**
![screenshot_2018-07-14 economic dashboard](https://user-images.githubusercontent.com/20679274/42725183-2c36ff30-8788-11e8-9a32-9e82c5124dd4.png)

**Comment by ivanminutillo** [comment]
hey @MichalisKas , this issue is related #26 , since line-break is one of the features we would have, if we introduce markdown syntax on the app. 
I will close this one and keep the conversation  open in the other 👍
