### ISSUE TITLE
Payment switch is set wrong when editing a contribution

### ISSUE THREAD

**Issue by MichalisKas** [opencooperativeecosystem/fc-dashboard#32]
**Describe the bug**
When you edit a previously logged contribution the payment switch appear OFF, regardless the initial state for Payed or Voluntary tasks.
Even, if you chose a Payed contribution, edit that and leave the switch untouched, the state of Payed/Voluntary doesn't change.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any payed contribution
2. Click on 'Edit'
3. Watch that the Payment switch is set to OFF
4. Even if you 'Publish" like that the contribution remains as "Payed"

**Expected behavior**
Payment switch should follow the behaviour of its previous setting.

**Screenshots**
![screenshot_2018-07-15 economic dashboard](https://user-images.githubusercontent.com/20679274/42734385-911287ee-884b-11e8-9d8b-0c2bc44c2d68.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version: 61.0.1 (64-bit)

**Comment by ivanminutillo** [comment]
fixed, thanks :)
