### ISSUE TITLE
Need a way to enter Produce events

### ISSUE THREAD

**Issue by fosterlynn** [opencooperativeecosystem/fc-dashboard#4]
In order for the I-P-O process chains to be able to hook together, the user needs to be able to log the produced resource for a process.  (Doesn't matter right now for OCW, but will matter when anyone keeps inventory or needs to chain the processes together - use this output as another process's input.)

Right now, clicking on the Output does nothing.

This is what the old OCP looks like.  Note that the commitment allows 2 options, to create a new resource and to add to an existing resource.  This example also has the logged event.

We can define what data elements to show when you do it.

![out-old](https://user-images.githubusercontent.com/3776081/41487000-6801b638-70ac-11e8-931c-73f92115da92.png)

**Comment by ivanminutillo** [comment]
ok few questions since I am going to address this issue soon...

1. I'd like to understand more the difference between 
  - create a new resource
  - Add to an existing resource

2. What does it means "this example also has the logged event" ?

3. How precisely creating an output will allow the I-P-O process chains to be able to hook together ?

**Comment by fosterlynn** [comment]
>I'd like to understand more the difference between
>create a new resource
>Add to an existing resource

This applies to "stock" resources, where you basically have a pile (or bin or pallet or whatever) of some quantity of a resource, and it doesn't matter the exact identity of any "touchable" resource, like it is 1L jars of tomato sauce.  If you already have 100 of these jars, and a process produces another 150 jars of the same 1L tomato sauce, the produce event will add to an existing resource, and you will have 250 jars of 1L tomato sauce.

Creating a new resource means there is nothing yet in inventory of that resource classification.  Or it could mean that the resource is serialized or tracked by lot, so that lot 2222 of 1L jars tomato sauce is a different resource than lot 2223 of 1L jars tomato sauce.  Then the process that produced lot 2223 creates a new resource.

>What does it means "this example also has the logged event" ?

Just pointing out that the screen print has both the commitment and the "produce" event.

>How precisely creating an output will allow the I-P-O process chains to be able to hook together ?

If one process creates 100 1L jars of tomato sauce lot 2222, and another process consumes 20 jars of 1L tomato sauce lot 2222, then those processes are "hooked together" because there is a resource flow.  

Or, if one process produces document XYZ, and another process cites document XYZ because it is translating it, that will similarly create a resource flow between the processes.

**Comment by ivanminutillo** [comment]
thanks!
In order to have a resource-flow, should we make mandatory to add an output on each process?

**Comment by fosterlynn** [comment]
>In order to have a resource-flow, should we make mandatory to add an output on each process?

My opinion is no.  Many administrative tasks have such a general output that it isn't worth documenting in that way, unless you really need to track the flow for a particular reason.  And also in general, I think best not to make things mandatory, and people can use it as best suits their purposes, and it will develop through practice.

If people want to keep track of inventory, or to be able to track the provenance of anything to understand fairness or quality or safety, or pay based on all contributions back in history, then they will log outputs and non-work inputs.  And if this eventually develops into more of a connected economy and people want to understand more the resource flows in their community, say to make things more fair, that might lead to more desire to log outputs and non-work inputs.
