### ISSUE TITLE
Way to see finished processes

### ISSUE THREAD

**Issue by fosterlynn** [opencooperativeecosystem/fc-dashboard#5]
We need to start "finishing" processes so that there isn't so much old data hanging around in the UI, both agent and OCP original.  OCP now take so long to load, it is super annoying, especially on the My Work page in the old NRP "admin app".

I think first we need to provide a separate report or way to see finished processes and plans.  Then we can ask people to finish the old processes.

**Comment by ivanminutillo** [comment]
other than that, I think it is a bad UX, that in order to set a plan finished, a user needs to set each process completed, it is counterintuitive.
I'd like to have a method on graphQl to set a plan completed directly, independently from the processes status

**Comment by ivanminutillo** [comment]
In the meantime I've released the possibility to filter plans, as in this screenshot:
<img width="337" alt="screen shot 2018-07-15 at 18 49 47" src="https://user-images.githubusercontent.com/1852065/42767338-0b262230-891d-11e8-9016-d3bbb2700f86.png">
I leave this issue open to discuss about a better way to handle plan status :)
