### ISSUE TITLE
Default unit when creating a commitment

### ISSUE THREAD

**Issue by fosterlynn** [opencooperativeecosystem/fc-dashboard#8]
When creating a new commitment, once the user has selected the resource classification, you can get the unit from that, and at least default that unit.  In OCP, it defaults but allows other selections.  I'm not totally sure we should even allow entry of the unit on a commitment, but I suppose it is best to leave it flexible in case the resource classification unit is wrong, which does happen.

**Comment by ivanminutillo** [comment]
yeah, eg right now translation default unit is "words", instead in OCW is inputted as "hours".
Can we assign several units to same resource?
I would prefer to tie resource to units, instead that allows general selections

**Comment by fosterlynn** [comment]
>Can we assign several units to same resource?

No, one unit per resource type (classification), and so one per resource, since it inherits the unit from the resource classification.  Except, you can have a unit and a unit of use for things like equipment, where the unit is probably 'each', and the unit of use might be 'hours' for example.

Note, the above is true in OCP, but not in VF.  But in either case, you can have only one unit (and one current quantity) per resource.
