### ISSUE TITLE
Misc. small things

### ISSUE THREAD

**Issue by fosterlynn** [opencooperativeecosystem/fc-dashboard#9]
1. Creating a plan, the plan name is so dark, I don't notice it, and can't read the gray on it either.  If it matched the other fields, that would be good.

2. I created a plan (processes, no commitments, no events).  It doesn't show on my dashboard view, even though I created it, which is confusing.  Maybe we should include in that list plans created by the agent? (Not sure what the rules are right now.) (It does show up other places.)

3. I think this modal to archive means to delete, need to change the word.  And, you could not show the button at all if there are events.  (There is a isDeletable() method now on plan.)  Same on process, should say "delete" rather than "archive".
![agent-archive](https://user-images.githubusercontent.com/3776081/42126706-9ae99498-7c51-11e8-90da-f60cfac9d911.png)

4. Messages overlaid what I needed to see, just an annoyance.
![agent-overlay](https://user-images.githubusercontent.com/3776081/42126708-9ecb46e2-7c51-11e8-9cb0-7a40ed6bcba5.png)

5. Would be nice to have rollover messages on the symbols.

6. I can't figure out how to get back my left menu back.  It is on Create Plan from things I just did.

**Comment by MichalisKas** [comment]
3. Agree. I think these 3 stages are enough:
(a) On-going (incomplete)
(b) Finished (completed)
(c) Deleted
Finished plans can then be considered as archived and may be found on a separate section.

4. Yes, happened to me several times already. Maybe could restrict their lenght?
Also they could just disappear automatically after couple of seconds, as sometimes you get 3-4 in a row and is annoying to have to delete them manually.

**Comment by MichalisKas** [comment]
2. Yes, I think they need to show on the Plans column (but not on the Diary, which is meant for contributions)

**Comment by ivanminutillo** [comment]
1. fixed
2. This one was already discussed and fixed in a separate issue (not tracked on github), am I right?
3. Agree with the behaviour described by @MichalisKas 
4. Agree, they should delete after 3seconds, and if you want to delete it before, you can click on the cross icon on the right.
6. You can toggle the sidebar clicking on the hamburger menu on the top left :)
